name: 'HorseEnhancer'
version: '2.1.2'
api-version: '1.18'
main: 'com.nevakanezah.horseenhancer.HorseEnhancerMain'
authors:
  - 'Nevakanezah'
  - 'AFlyingPoro'
website: 'https://github.com/Nevakanezah/HorseEnhancer'

libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.22'
  - 'net.kyori:adventure-platform-bukkit:4.2.0'
  - 'com.zaxxer:HikariCP:5.0.1'
  - 'org.xerial:sqlite-jdbc:3.40.0.0'
  - 'space.arim.dazzleconf:dazzleconf-ext-snakeyaml:1.3.0-M1'
  - 'org.flywaydb:flyway-core:9.10.2'

commands:
  horseenhancer:
    aliases:
      - he
    usage: 'Use ''/<command> help'' for a list of commands.'
