name: 'HorseEnhancer'
version: '2.0.0'
api-version: '1.18'
main: 'com.nevakanezah.horseenhancer.HorseEnhancerMain'
authors:
  - 'Nevakanezah'
  - 'AFlyingPoro'
website: 'https://github.com/Nevakanezah/HorseEnhancer'

libraries:
  - 'com.zaxxer:HikariCP:5.0.1'
  - 'org.xerial:sqlite-jdbc:3.39.3.0'

commands:
  horseenhancer:
    aliases:
      - he
    usage: 'Use ''/<command> help'' for a list of commands.'
